[versions]

jvm-dependency-conflict-resolution = "2.2"

[libraries]

[libraries.jvm-dependency-conflict-resolution-gradle-plugin-dependency]
module = "org.gradlex:jvm-dependency-conflict-resolution"
version.ref = "jvm-dependency-conflict-resolution"
